// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: service.proto

package service

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutionState int32

const (
	ExecutionState_EXECUTION_STATE_UNSPECIFIED ExecutionState = 0
	ExecutionState_PENDING                     ExecutionState = 1
	ExecutionState_RUNNING                     ExecutionState = 2
	ExecutionState_SUCCESS                     ExecutionState = 3
	ExecutionState_FAILED                      ExecutionState = 4
)

// Enum value maps for ExecutionState.
var (
	ExecutionState_name = map[int32]string{
		0: "EXECUTION_STATE_UNSPECIFIED",
		1: "PENDING",
		2: "RUNNING",
		3: "SUCCESS",
		4: "FAILED",
	}
	ExecutionState_value = map[string]int32{
		"EXECUTION_STATE_UNSPECIFIED": 0,
		"PENDING":                     1,
		"RUNNING":                     2,
		"SUCCESS":                     3,
		"FAILED":                      4,
	}
)

func (x ExecutionState) Enum() *ExecutionState {
	p := new(ExecutionState)
	*p = x
	return p
}

func (x ExecutionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionState) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[0].Descriptor()
}

func (ExecutionState) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[0]
}

func (x ExecutionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionState.Descriptor instead.
func (ExecutionState) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

type WorkflowDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Yaml          string                 `protobuf:"bytes,3,opt,name=yaml,proto3" json:"yaml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowDefinition) Reset() {
	*x = WorkflowDefinition{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowDefinition) ProtoMessage() {}

func (x *WorkflowDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowDefinition.ProtoReflect.Descriptor instead.
func (*WorkflowDefinition) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *WorkflowDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkflowDefinition) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *WorkflowDefinition) GetYaml() string {
	if x != nil {
		return x.Yaml
	}
	return ""
}

type ValidateWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Workflow      *WorkflowDefinition    `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateWorkflowRequest) Reset() {
	*x = ValidateWorkflowRequest{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateWorkflowRequest) ProtoMessage() {}

func (x *ValidateWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateWorkflowRequest.ProtoReflect.Descriptor instead.
func (*ValidateWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateWorkflowRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ValidateWorkflowRequest) GetWorkflow() *WorkflowDefinition {
	if x != nil {
		return x.Workflow
	}
	return nil
}

type ValidateWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors        []string               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateWorkflowResponse) Reset() {
	*x = ValidateWorkflowResponse{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateWorkflowResponse) ProtoMessage() {}

func (x *ValidateWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateWorkflowResponse.ProtoReflect.Descriptor instead.
func (*ValidateWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateWorkflowResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateWorkflowResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type RegisterWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Workflow      *WorkflowDefinition    `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkflowRequest) Reset() {
	*x = RegisterWorkflowRequest{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkflowRequest) ProtoMessage() {}

func (x *RegisterWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkflowRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterWorkflowRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *RegisterWorkflowRequest) GetWorkflow() *WorkflowDefinition {
	if x != nil {
		return x.Workflow
	}
	return nil
}

type RegisterWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkflowResponse) Reset() {
	*x = RegisterWorkflowResponse{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkflowResponse) ProtoMessage() {}

func (x *RegisterWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkflowResponse.ProtoReflect.Descriptor instead.
func (*RegisterWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterWorkflowResponse) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type ListWorkflowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowsRequest) Reset() {
	*x = ListWorkflowsRequest{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsRequest) ProtoMessage() {}

func (x *ListWorkflowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsRequest.ProtoReflect.Descriptor instead.
func (*ListWorkflowsRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListWorkflowsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListWorkflowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflows     []*WorkflowInfo        `protobuf:"bytes,1,rep,name=workflows,proto3" json:"workflows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowsResponse) Reset() {
	*x = ListWorkflowsResponse{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsResponse) ProtoMessage() {}

func (x *ListWorkflowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsResponse.ProtoReflect.Descriptor instead.
func (*ListWorkflowsResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListWorkflowsResponse) GetWorkflows() []*WorkflowInfo {
	if x != nil {
		return x.Workflows
	}
	return nil
}

type WorkflowInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	ProjectId     string                 `protobuf:"bytes,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowInfo) Reset() {
	*x = WorkflowInfo{}
	mi := &file_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowInfo) ProtoMessage() {}

func (x *WorkflowInfo) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowInfo.ProtoReflect.Descriptor instead.
func (*WorkflowInfo) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *WorkflowInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkflowInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkflowInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *WorkflowInfo) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type GetWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowRequest) Reset() {
	*x = GetWorkflowRequest{}
	mi := &file_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowRequest) ProtoMessage() {}

func (x *GetWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetWorkflowRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type GetWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflow      *WorkflowInfo          `protobuf:"bytes,1,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Yaml          string                 `protobuf:"bytes,2,opt,name=yaml,proto3" json:"yaml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowResponse) Reset() {
	*x = GetWorkflowResponse{}
	mi := &file_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowResponse) ProtoMessage() {}

func (x *GetWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowResponse.ProtoReflect.Descriptor instead.
func (*GetWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetWorkflowResponse) GetWorkflow() *WorkflowInfo {
	if x != nil {
		return x.Workflow
	}
	return nil
}

func (x *GetWorkflowResponse) GetYaml() string {
	if x != nil {
		return x.Yaml
	}
	return ""
}

type StartWorkflowRequest struct {
	state           protoimpl.MessageState     `protogen:"open.v1"`
	ProjectId       string                     `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	WorkflowId      string                     `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Inputs          map[string]*structpb.Value `protobuf:"bytes,3,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ClientRequestId string                     `protobuf:"bytes,4,opt,name=client_request_id,json=clientRequestId,proto3" json:"client_request_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StartWorkflowRequest) Reset() {
	*x = StartWorkflowRequest{}
	mi := &file_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkflowRequest) ProtoMessage() {}

func (x *StartWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkflowRequest.ProtoReflect.Descriptor instead.
func (*StartWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{10}
}

func (x *StartWorkflowRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *StartWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *StartWorkflowRequest) GetInputs() map[string]*structpb.Value {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *StartWorkflowRequest) GetClientRequestId() string {
	if x != nil {
		return x.ClientRequestId
	}
	return ""
}

type StartWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWorkflowResponse) Reset() {
	*x = StartWorkflowResponse{}
	mi := &file_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkflowResponse) ProtoMessage() {}

func (x *StartWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkflowResponse.ProtoReflect.Descriptor instead.
func (*StartWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{11}
}

func (x *StartWorkflowResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *StartWorkflowResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type GetExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ExecutionId   string                 `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionRequest) Reset() {
	*x = GetExecutionRequest{}
	mi := &file_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionRequest) ProtoMessage() {}

func (x *GetExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionRequest.ProtoReflect.Descriptor instead.
func (*GetExecutionRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetExecutionRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetExecutionRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type GetExecutionResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	State         ExecutionState             `protobuf:"varint,1,opt,name=state,proto3,enum=workflow.v1.ExecutionState" json:"state,omitempty"`
	Inputs        map[string]*structpb.Value `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Outputs       map[string]*structpb.Value `protobuf:"bytes,3,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error         string                     `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionResponse) Reset() {
	*x = GetExecutionResponse{}
	mi := &file_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionResponse) ProtoMessage() {}

func (x *GetExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionResponse.ProtoReflect.Descriptor instead.
func (*GetExecutionResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetExecutionResponse) GetState() ExecutionState {
	if x != nil {
		return x.State
	}
	return ExecutionState_EXECUTION_STATE_UNSPECIFIED
}

func (x *GetExecutionResponse) GetInputs() map[string]*structpb.Value {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *GetExecutionResponse) GetOutputs() map[string]*structpb.Value {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *GetExecutionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Module struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name      string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Version   string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Runtime   string                 `protobuf:"bytes,5,opt,name=runtime,proto3" json:"runtime,omitempty"` // http | docker
	// Types that are valid to be assigned to Spec:
	//
	//	*Module_Http
	//	*Module_ContainerRegistry
	Spec          isModule_Spec              `protobuf_oneof:"spec"`
	Inputs        map[string]*structpb.Value `protobuf:"bytes,8,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Outputs       map[string]*structpb.Value `protobuf:"bytes,9,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RuntimeConfig *structpb.Struct           `protobuf:"bytes,10,opt,name=runtime_config,json=runtimeConfig,proto3" json:"runtime_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Module) Reset() {
	*x = Module{}
	mi := &file_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Module) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Module) ProtoMessage() {}

func (x *Module) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Module.ProtoReflect.Descriptor instead.
func (*Module) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{14}
}

func (x *Module) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Module) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Module) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Module) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Module) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *Module) GetSpec() isModule_Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Module) GetHttp() *HttpModuleSpec {
	if x != nil {
		if x, ok := x.Spec.(*Module_Http); ok {
			return x.Http
		}
	}
	return nil
}

func (x *Module) GetContainerRegistry() *ContainerRegistryModuleSpec {
	if x != nil {
		if x, ok := x.Spec.(*Module_ContainerRegistry); ok {
			return x.ContainerRegistry
		}
	}
	return nil
}

func (x *Module) GetInputs() map[string]*structpb.Value {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *Module) GetOutputs() map[string]*structpb.Value {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *Module) GetRuntimeConfig() *structpb.Struct {
	if x != nil {
		return x.RuntimeConfig
	}
	return nil
}

type isModule_Spec interface {
	isModule_Spec()
}

type Module_Http struct {
	Http *HttpModuleSpec `protobuf:"bytes,6,opt,name=http,proto3,oneof"`
}

type Module_ContainerRegistry struct {
	ContainerRegistry *ContainerRegistryModuleSpec `protobuf:"bytes,7,opt,name=container_registry,json=containerRegistry,proto3,oneof"`
}

func (*Module_Http) isModule_Spec() {}

func (*Module_ContainerRegistry) isModule_Spec() {}

type HttpModuleSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	QueryParams   map[string]string      `protobuf:"bytes,4,rep,name=query_params,json=queryParams,proto3" json:"query_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BodyTemplate  *structpb.Struct       `protobuf:"bytes,5,opt,name=body_template,json=bodyTemplate,proto3" json:"body_template,omitempty"`
	Auth          *HttpAuth              `protobuf:"bytes,6,opt,name=auth,proto3" json:"auth,omitempty"`
	OutputMapping *structpb.Struct       `protobuf:"bytes,7,opt,name=output_mapping,json=outputMapping,proto3" json:"output_mapping,omitempty"`
	RetryCount    int32                  `protobuf:"varint,8,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	TimeoutMs     int32                  `protobuf:"varint,9,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpModuleSpec) Reset() {
	*x = HttpModuleSpec{}
	mi := &file_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpModuleSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpModuleSpec) ProtoMessage() {}

func (x *HttpModuleSpec) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpModuleSpec.ProtoReflect.Descriptor instead.
func (*HttpModuleSpec) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{15}
}

func (x *HttpModuleSpec) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpModuleSpec) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HttpModuleSpec) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpModuleSpec) GetQueryParams() map[string]string {
	if x != nil {
		return x.QueryParams
	}
	return nil
}

func (x *HttpModuleSpec) GetBodyTemplate() *structpb.Struct {
	if x != nil {
		return x.BodyTemplate
	}
	return nil
}

func (x *HttpModuleSpec) GetAuth() *HttpAuth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *HttpModuleSpec) GetOutputMapping() *structpb.Struct {
	if x != nil {
		return x.OutputMapping
	}
	return nil
}

func (x *HttpModuleSpec) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *HttpModuleSpec) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type HttpAuth struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*HttpAuth_ApiKey
	//	*HttpAuth_Bearer
	//	*HttpAuth_Oauth2
	Type          isHttpAuth_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpAuth) Reset() {
	*x = HttpAuth{}
	mi := &file_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpAuth) ProtoMessage() {}

func (x *HttpAuth) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpAuth.ProtoReflect.Descriptor instead.
func (*HttpAuth) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{16}
}

func (x *HttpAuth) GetType() isHttpAuth_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *HttpAuth) GetApiKey() *ApiKeyAuth {
	if x != nil {
		if x, ok := x.Type.(*HttpAuth_ApiKey); ok {
			return x.ApiKey
		}
	}
	return nil
}

func (x *HttpAuth) GetBearer() *BearerAuth {
	if x != nil {
		if x, ok := x.Type.(*HttpAuth_Bearer); ok {
			return x.Bearer
		}
	}
	return nil
}

func (x *HttpAuth) GetOauth2() *OAuth2Auth {
	if x != nil {
		if x, ok := x.Type.(*HttpAuth_Oauth2); ok {
			return x.Oauth2
		}
	}
	return nil
}

type isHttpAuth_Type interface {
	isHttpAuth_Type()
}

type HttpAuth_ApiKey struct {
	ApiKey *ApiKeyAuth `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3,oneof"`
}

type HttpAuth_Bearer struct {
	Bearer *BearerAuth `protobuf:"bytes,2,opt,name=bearer,proto3,oneof"`
}

type HttpAuth_Oauth2 struct {
	Oauth2 *OAuth2Auth `protobuf:"bytes,3,opt,name=oauth2,proto3,oneof"`
}

func (*HttpAuth_ApiKey) isHttpAuth_Type() {}

func (*HttpAuth_Bearer) isHttpAuth_Type() {}

func (*HttpAuth_Oauth2) isHttpAuth_Type() {}

type ApiKeyAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        string                 `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKeyAuth) Reset() {
	*x = ApiKeyAuth{}
	mi := &file_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKeyAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeyAuth) ProtoMessage() {}

func (x *ApiKeyAuth) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeyAuth.ProtoReflect.Descriptor instead.
func (*ApiKeyAuth) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{17}
}

func (x *ApiKeyAuth) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *ApiKeyAuth) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type BearerAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BearerAuth) Reset() {
	*x = BearerAuth{}
	mi := &file_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BearerAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BearerAuth) ProtoMessage() {}

func (x *BearerAuth) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BearerAuth.ProtoReflect.Descriptor instead.
func (*BearerAuth) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{18}
}

func (x *BearerAuth) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type OAuth2Auth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenUrl      string                 `protobuf:"bytes,1,opt,name=token_url,json=tokenUrl,proto3" json:"token_url,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,3,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	Scope         string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuth2Auth) Reset() {
	*x = OAuth2Auth{}
	mi := &file_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuth2Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuth2Auth) ProtoMessage() {}

func (x *OAuth2Auth) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuth2Auth.ProtoReflect.Descriptor instead.
func (*OAuth2Auth) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{19}
}

func (x *OAuth2Auth) GetTokenUrl() string {
	if x != nil {
		return x.TokenUrl
	}
	return ""
}

func (x *OAuth2Auth) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *OAuth2Auth) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *OAuth2Auth) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type ContainerRegistryModuleSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Command       []string               `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	Env           map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Cpu           string                 `protobuf:"bytes,4,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        string                 `protobuf:"bytes,5,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerRegistryModuleSpec) Reset() {
	*x = ContainerRegistryModuleSpec{}
	mi := &file_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerRegistryModuleSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerRegistryModuleSpec) ProtoMessage() {}

func (x *ContainerRegistryModuleSpec) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerRegistryModuleSpec.ProtoReflect.Descriptor instead.
func (*ContainerRegistryModuleSpec) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{20}
}

func (x *ContainerRegistryModuleSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerRegistryModuleSpec) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ContainerRegistryModuleSpec) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ContainerRegistryModuleSpec) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *ContainerRegistryModuleSpec) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

type RegisterModuleRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ProjectId string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version   string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Runtime   string                 `protobuf:"bytes,4,opt,name=runtime,proto3" json:"runtime,omitempty"`
	// Types that are valid to be assigned to Spec:
	//
	//	*RegisterModuleRequest_Http
	//	*RegisterModuleRequest_ContainerRegistry
	Spec          isRegisterModuleRequest_Spec `protobuf_oneof:"spec"`
	Inputs        map[string]*structpb.Value   `protobuf:"bytes,7,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Outputs       map[string]*structpb.Value   `protobuf:"bytes,8,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterModuleRequest) Reset() {
	*x = RegisterModuleRequest{}
	mi := &file_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterModuleRequest) ProtoMessage() {}

func (x *RegisterModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterModuleRequest.ProtoReflect.Descriptor instead.
func (*RegisterModuleRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{21}
}

func (x *RegisterModuleRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *RegisterModuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterModuleRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterModuleRequest) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *RegisterModuleRequest) GetSpec() isRegisterModuleRequest_Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *RegisterModuleRequest) GetHttp() *HttpModuleSpec {
	if x != nil {
		if x, ok := x.Spec.(*RegisterModuleRequest_Http); ok {
			return x.Http
		}
	}
	return nil
}

func (x *RegisterModuleRequest) GetContainerRegistry() *ContainerRegistryModuleSpec {
	if x != nil {
		if x, ok := x.Spec.(*RegisterModuleRequest_ContainerRegistry); ok {
			return x.ContainerRegistry
		}
	}
	return nil
}

func (x *RegisterModuleRequest) GetInputs() map[string]*structpb.Value {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *RegisterModuleRequest) GetOutputs() map[string]*structpb.Value {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type isRegisterModuleRequest_Spec interface {
	isRegisterModuleRequest_Spec()
}

type RegisterModuleRequest_Http struct {
	Http *HttpModuleSpec `protobuf:"bytes,5,opt,name=http,proto3,oneof"`
}

type RegisterModuleRequest_ContainerRegistry struct {
	ContainerRegistry *ContainerRegistryModuleSpec `protobuf:"bytes,6,opt,name=container_registry,json=containerRegistry,proto3,oneof"`
}

func (*RegisterModuleRequest_Http) isRegisterModuleRequest_Spec() {}

func (*RegisterModuleRequest_ContainerRegistry) isRegisterModuleRequest_Spec() {}

type RegisterModuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleId      string                 `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterModuleResponse) Reset() {
	*x = RegisterModuleResponse{}
	mi := &file_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterModuleResponse) ProtoMessage() {}

func (x *RegisterModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterModuleResponse.ProtoReflect.Descriptor instead.
func (*RegisterModuleResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{22}
}

func (x *RegisterModuleResponse) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

type GetModuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModuleRequest) Reset() {
	*x = GetModuleRequest{}
	mi := &file_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModuleRequest) ProtoMessage() {}

func (x *GetModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModuleRequest.ProtoReflect.Descriptor instead.
func (*GetModuleRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{23}
}

func (x *GetModuleRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetModuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetModuleRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetModuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        *Module                `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModuleResponse) Reset() {
	*x = GetModuleResponse{}
	mi := &file_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModuleResponse) ProtoMessage() {}

func (x *GetModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModuleResponse.ProtoReflect.Descriptor instead.
func (*GetModuleResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{24}
}

func (x *GetModuleResponse) GetModule() *Module {
	if x != nil {
		return x.Module
	}
	return nil
}

type ListModulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModulesRequest) Reset() {
	*x = ListModulesRequest{}
	mi := &file_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModulesRequest) ProtoMessage() {}

func (x *ListModulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModulesRequest.ProtoReflect.Descriptor instead.
func (*ListModulesRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{25}
}

func (x *ListModulesRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListModulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Modules       []*Module              `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModulesResponse) Reset() {
	*x = ListModulesResponse{}
	mi := &file_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModulesResponse) ProtoMessage() {}

func (x *ListModulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModulesResponse.ProtoReflect.Descriptor instead.
func (*ListModulesResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{26}
}

func (x *ListModulesResponse) GetModules() []*Module {
	if x != nil {
		return x.Modules
	}
	return nil
}

type ListExecutionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"` // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExecutionsRequest) Reset() {
	*x = ListExecutionsRequest{}
	mi := &file_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExecutionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExecutionsRequest) ProtoMessage() {}

func (x *ListExecutionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExecutionsRequest.ProtoReflect.Descriptor instead.
func (*ListExecutionsRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{27}
}

func (x *ListExecutionsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ListExecutionsRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type ExecutionInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkflowId      string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	WorkflowName    string                 `protobuf:"bytes,7,opt,name=workflow_name,json=workflowName,proto3" json:"workflow_name,omitempty"` // Workflow name for display
	ProjectId       string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ClientRequestId string                 `protobuf:"bytes,4,opt,name=client_request_id,json=clientRequestId,proto3" json:"client_request_id,omitempty"`
	State           string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Error           string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecutionInfo) Reset() {
	*x = ExecutionInfo{}
	mi := &file_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionInfo) ProtoMessage() {}

func (x *ExecutionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionInfo.ProtoReflect.Descriptor instead.
func (*ExecutionInfo) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{28}
}

func (x *ExecutionInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExecutionInfo) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *ExecutionInfo) GetWorkflowName() string {
	if x != nil {
		return x.WorkflowName
	}
	return ""
}

func (x *ExecutionInfo) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ExecutionInfo) GetClientRequestId() string {
	if x != nil {
		return x.ClientRequestId
	}
	return ""
}

func (x *ExecutionInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ExecutionInfo) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListExecutionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Executions    []*ExecutionInfo       `protobuf:"bytes,1,rep,name=executions,proto3" json:"executions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExecutionsResponse) Reset() {
	*x = ListExecutionsResponse{}
	mi := &file_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExecutionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExecutionsResponse) ProtoMessage() {}

func (x *ListExecutionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExecutionsResponse.ProtoReflect.Descriptor instead.
func (*ListExecutionsResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{29}
}

func (x *ListExecutionsResponse) GetExecutions() []*ExecutionInfo {
	if x != nil {
		return x.Executions
	}
	return nil
}

type GetDashboardStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardStatsRequest) Reset() {
	*x = GetDashboardStatsRequest{}
	mi := &file_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardStatsRequest) ProtoMessage() {}

func (x *GetDashboardStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardStatsRequest.ProtoReflect.Descriptor instead.
func (*GetDashboardStatsRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{30}
}

func (x *GetDashboardStatsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type GetDashboardStatsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalWorkflows    int64                  `protobuf:"varint,1,opt,name=total_workflows,json=totalWorkflows,proto3" json:"total_workflows,omitempty"`
	TotalExecutions   int64                  `protobuf:"varint,2,opt,name=total_executions,json=totalExecutions,proto3" json:"total_executions,omitempty"`
	RunningExecutions int64                  `protobuf:"varint,3,opt,name=running_executions,json=runningExecutions,proto3" json:"running_executions,omitempty"`
	SuccessRate       float64                `protobuf:"fixed64,4,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"` // Percentage (0-100)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetDashboardStatsResponse) Reset() {
	*x = GetDashboardStatsResponse{}
	mi := &file_service_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardStatsResponse) ProtoMessage() {}

func (x *GetDashboardStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardStatsResponse.ProtoReflect.Descriptor instead.
func (*GetDashboardStatsResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{31}
}

func (x *GetDashboardStatsResponse) GetTotalWorkflows() int64 {
	if x != nil {
		return x.TotalWorkflows
	}
	return 0
}

func (x *GetDashboardStatsResponse) GetTotalExecutions() int64 {
	if x != nil {
		return x.TotalExecutions
	}
	return 0
}

func (x *GetDashboardStatsResponse) GetRunningExecutions() int64 {
	if x != nil {
		return x.RunningExecutions
	}
	return 0
}

func (x *GetDashboardStatsResponse) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

type GetExecutionTimelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ExecutionId   string                 `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"` // UUID as string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionTimelineRequest) Reset() {
	*x = GetExecutionTimelineRequest{}
	mi := &file_service_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionTimelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionTimelineRequest) ProtoMessage() {}

func (x *GetExecutionTimelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionTimelineRequest.ProtoReflect.Descriptor instead.
func (*GetExecutionTimelineRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{32}
}

func (x *GetExecutionTimelineRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetExecutionTimelineRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type GetExecutionTimelineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timeline      *ExecutionTimeline     `protobuf:"bytes,1,opt,name=timeline,proto3" json:"timeline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionTimelineResponse) Reset() {
	*x = GetExecutionTimelineResponse{}
	mi := &file_service_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionTimelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionTimelineResponse) ProtoMessage() {}

func (x *GetExecutionTimelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionTimelineResponse.ProtoReflect.Descriptor instead.
func (*GetExecutionTimelineResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{33}
}

func (x *GetExecutionTimelineResponse) GetTimeline() *ExecutionTimeline {
	if x != nil {
		return x.Timeline
	}
	return nil
}

type ExecutionTimeline struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	ExecutionId   string                    `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	ProjectId     string                    `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	WorkflowId    string                    `protobuf:"bytes,3,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Status        string                    `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt     *timestamppb.Timestamp    `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp    `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Events        []*ExecutionTimelineEvent `protobuf:"bytes,7,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionTimeline) Reset() {
	*x = ExecutionTimeline{}
	mi := &file_service_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionTimeline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionTimeline) ProtoMessage() {}

func (x *ExecutionTimeline) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionTimeline.ProtoReflect.Descriptor instead.
func (*ExecutionTimeline) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{34}
}

func (x *ExecutionTimeline) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecutionTimeline) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ExecutionTimeline) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *ExecutionTimeline) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecutionTimeline) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ExecutionTimeline) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *ExecutionTimeline) GetEvents() []*ExecutionTimelineEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type ExecutionTimelineEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Executor      string                 `protobuf:"bytes,4,opt,name=executor,proto3" json:"executor,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	DurationMs    int64                  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionTimelineEvent) Reset() {
	*x = ExecutionTimelineEvent{}
	mi := &file_service_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionTimelineEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionTimelineEvent) ProtoMessage() {}

func (x *ExecutionTimelineEvent) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionTimelineEvent.ProtoReflect.Descriptor instead.
func (*ExecutionTimelineEvent) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{35}
}

func (x *ExecutionTimelineEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ExecutionTimelineEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ExecutionTimelineEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ExecutionTimelineEvent) GetExecutor() string {
	if x != nil {
		return x.Executor
	}
	return ""
}

func (x *ExecutionTimelineEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecutionTimelineEvent) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ExecutionTimelineEvent) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\vworkflow.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x93\x01\n" +
	"\x12WorkflowDefinition\x12\x18\n" +
	"\x04name\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x04name\x12\x1e\n" +
	"\aversion\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\aversion\x12C\n" +
	"\x04yaml\x18\x03 \x01(\tB/\x92A(2&Raw workflow definition in YAML format\xe2A\x01\x02R\x04yaml\"u\n" +
	"\x17ValidateWorkflowRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12;\n" +
	"\bworkflow\x18\x02 \x01(\v2\x1f.workflow.v1.WorkflowDefinitionR\bworkflow\"H\n" +
	"\x18ValidateWorkflowResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors\"\x81\x01\n" +
	"\x17RegisterWorkflowRequest\x12#\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\tprojectId\x12A\n" +
	"\bworkflow\x18\x02 \x01(\v2\x1f.workflow.v1.WorkflowDefinitionB\x04\xe2A\x01\x02R\bworkflow\";\n" +
	"\x18RegisterWorkflowResponse\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\";\n" +
	"\x14ListWorkflowsRequest\x12#\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\tprojectId\"P\n" +
	"\x15ListWorkflowsResponse\x127\n" +
	"\tworkflows\x18\x01 \x03(\v2\x19.workflow.v1.WorkflowInfoR\tworkflows\"k\n" +
	"\fWorkflowInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"project_id\x18\x04 \x01(\tR\tprojectId\"`\n" +
	"\x12GetWorkflowRequest\x12#\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\tprojectId\x12%\n" +
	"\vworkflow_id\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\n" +
	"workflowId\"`\n" +
	"\x13GetWorkflowResponse\x125\n" +
	"\bworkflow\x18\x01 \x01(\v2\x19.workflow.v1.WorkflowInfoR\bworkflow\x12\x12\n" +
	"\x04yaml\x18\x02 \x01(\tR\x04yaml\"\xae\x02\n" +
	"\x14StartWorkflowRequest\x12#\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\tprojectId\x12%\n" +
	"\vworkflow_id\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\n" +
	"workflowId\x12E\n" +
	"\x06inputs\x18\x03 \x03(\v2-.workflow.v1.StartWorkflowRequest.InputsEntryR\x06inputs\x120\n" +
	"\x11client_request_id\x18\x04 \x01(\tB\x04\xe2A\x01\x02R\x0fclientRequestId\x1aQ\n" +
	"\vInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"P\n" +
	"\x15StartWorkflowResponse\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"c\n" +
	"\x13GetExecutionRequest\x12#\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\tprojectId\x12'\n" +
	"\fexecution_id\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\vexecutionId\"\x97\x03\n" +
	"\x14GetExecutionResponse\x121\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1b.workflow.v1.ExecutionStateR\x05state\x12E\n" +
	"\x06inputs\x18\x02 \x03(\v2-.workflow.v1.GetExecutionResponse.InputsEntryR\x06inputs\x12H\n" +
	"\aoutputs\x18\x03 \x03(\v2..workflow.v1.GetExecutionResponse.OutputsEntryR\aoutputs\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x1aQ\n" +
	"\vInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\x1aR\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"\xf1\x04\n" +
	"\x06Module\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x18\n" +
	"\aruntime\x18\x05 \x01(\tR\aruntime\x121\n" +
	"\x04http\x18\x06 \x01(\v2\x1b.workflow.v1.HttpModuleSpecH\x00R\x04http\x12Y\n" +
	"\x12container_registry\x18\a \x01(\v2(.workflow.v1.ContainerRegistryModuleSpecH\x00R\x11containerRegistry\x127\n" +
	"\x06inputs\x18\b \x03(\v2\x1f.workflow.v1.Module.InputsEntryR\x06inputs\x12:\n" +
	"\aoutputs\x18\t \x03(\v2 .workflow.v1.Module.OutputsEntryR\aoutputs\x12>\n" +
	"\x0eruntime_config\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\rruntimeConfig\x1aQ\n" +
	"\vInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\x1aR\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01B\x06\n" +
	"\x04spec\"\xb4\x04\n" +
	"\x0eHttpModuleSpec\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12B\n" +
	"\aheaders\x18\x03 \x03(\v2(.workflow.v1.HttpModuleSpec.HeadersEntryR\aheaders\x12O\n" +
	"\fquery_params\x18\x04 \x03(\v2,.workflow.v1.HttpModuleSpec.QueryParamsEntryR\vqueryParams\x12<\n" +
	"\rbody_template\x18\x05 \x01(\v2\x17.google.protobuf.StructR\fbodyTemplate\x12)\n" +
	"\x04auth\x18\x06 \x01(\v2\x15.workflow.v1.HttpAuthR\x04auth\x12>\n" +
	"\x0eoutput_mapping\x18\a \x01(\v2\x17.google.protobuf.StructR\routputMapping\x12\x1f\n" +
	"\vretry_count\x18\b \x01(\x05R\n" +
	"retryCount\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\t \x01(\x05R\ttimeoutMs\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10QueryParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xac\x01\n" +
	"\bHttpAuth\x122\n" +
	"\aapi_key\x18\x01 \x01(\v2\x17.workflow.v1.ApiKeyAuthH\x00R\x06apiKey\x121\n" +
	"\x06bearer\x18\x02 \x01(\v2\x17.workflow.v1.BearerAuthH\x00R\x06bearer\x121\n" +
	"\x06oauth2\x18\x03 \x01(\v2\x17.workflow.v1.OAuth2AuthH\x00R\x06oauth2B\x06\n" +
	"\x04type\":\n" +
	"\n" +
	"ApiKeyAuth\x12\x16\n" +
	"\x06header\x18\x01 \x01(\tR\x06header\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\"\n" +
	"\n" +
	"BearerAuth\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x81\x01\n" +
	"\n" +
	"OAuth2Auth\x12\x1b\n" +
	"\ttoken_url\x18\x01 \x01(\tR\btokenUrl\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x03 \x01(\tR\fclientSecret\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\"\xf4\x01\n" +
	"\x1bContainerRegistryModuleSpec\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12C\n" +
	"\x03env\x18\x03 \x03(\v21.workflow.v1.ContainerRegistryModuleSpec.EnvEntryR\x03env\x12\x10\n" +
	"\x03cpu\x18\x04 \x01(\tR\x03cpu\x12\x16\n" +
	"\x06memory\x18\x05 \x01(\tR\x06memory\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xce\x04\n" +
	"\x15RegisterModuleRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x18\n" +
	"\aruntime\x18\x04 \x01(\tR\aruntime\x121\n" +
	"\x04http\x18\x05 \x01(\v2\x1b.workflow.v1.HttpModuleSpecH\x00R\x04http\x12Y\n" +
	"\x12container_registry\x18\x06 \x01(\v2(.workflow.v1.ContainerRegistryModuleSpecH\x00R\x11containerRegistry\x12F\n" +
	"\x06inputs\x18\a \x03(\v2..workflow.v1.RegisterModuleRequest.InputsEntryR\x06inputs\x12I\n" +
	"\aoutputs\x18\b \x03(\v2/.workflow.v1.RegisterModuleRequest.OutputsEntryR\aoutputs\x1aQ\n" +
	"\vInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\x1aR\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01B\x06\n" +
	"\x04spec\"5\n" +
	"\x16RegisterModuleResponse\x12\x1b\n" +
	"\tmodule_id\x18\x01 \x01(\tR\bmoduleId\"_\n" +
	"\x10GetModuleRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"@\n" +
	"\x11GetModuleResponse\x12+\n" +
	"\x06module\x18\x01 \x01(\v2\x13.workflow.v1.ModuleR\x06module\"3\n" +
	"\x12ListModulesRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"D\n" +
	"\x13ListModulesResponse\x12-\n" +
	"\amodules\x18\x01 \x03(\v2\x13.workflow.v1.ModuleR\amodules\"W\n" +
	"\x15ListExecutionsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\"\xdc\x01\n" +
	"\rExecutionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12#\n" +
	"\rworkflow_name\x18\a \x01(\tR\fworkflowName\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\x12*\n" +
	"\x11client_request_id\x18\x04 \x01(\tR\x0fclientRequestId\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"T\n" +
	"\x16ListExecutionsResponse\x12:\n" +
	"\n" +
	"executions\x18\x01 \x03(\v2\x1a.workflow.v1.ExecutionInfoR\n" +
	"executions\"?\n" +
	"\x18GetDashboardStatsRequest\x12#\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\tprojectId\"\xc1\x01\n" +
	"\x19GetDashboardStatsResponse\x12'\n" +
	"\x0ftotal_workflows\x18\x01 \x01(\x03R\x0etotalWorkflows\x12)\n" +
	"\x10total_executions\x18\x02 \x01(\x03R\x0ftotalExecutions\x12-\n" +
	"\x12running_executions\x18\x03 \x01(\x03R\x11runningExecutions\x12!\n" +
	"\fsuccess_rate\x18\x04 \x01(\x01R\vsuccessRate\"_\n" +
	"\x1bGetExecutionTimelineRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12!\n" +
	"\fexecution_id\x18\x02 \x01(\tR\vexecutionId\"Z\n" +
	"\x1cGetExecutionTimelineResponse\x12:\n" +
	"\btimeline\x18\x01 \x01(\v2\x1e.workflow.v1.ExecutionTimelineR\btimeline\"\xc5\x02\n" +
	"\x11ExecutionTimeline\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x1f\n" +
	"\vworkflow_id\x18\x03 \x01(\tR\n" +
	"workflowId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12;\n" +
	"\x06events\x18\a \x03(\v2#.workflow.v1.ExecutionTimelineEventR\x06events\"\x89\x02\n" +
	"\x16ExecutionTimelineEvent\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bexecutor\x18\x04 \x01(\tR\bexecutor\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x03R\n" +
	"durationMs\x121\n" +
	"\apayload\x18\a \x01(\v2\x17.google.protobuf.StructR\apayload*d\n" +
	"\x0eExecutionState\x12\x1f\n" +
	"\x1bEXECUTION_STATE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\v\n" +
	"\aRUNNING\x10\x02\x12\v\n" +
	"\aSUCCESS\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x042\xc5\n" +
	"\n" +
	"\x0fWorkflowService\x12\x98\x01\n" +
	"\x10ValidateWorkflow\x12$.workflow.v1.ValidateWorkflowRequest\x1a%.workflow.v1.ValidateWorkflowResponse\"7\x82\xd3\xe4\x93\x021:\x01*\",/v1/projects/{project_id}/workflows:validate\x12\x8f\x01\n" +
	"\x10RegisterWorkflow\x12$.workflow.v1.RegisterWorkflowRequest\x1a%.workflow.v1.RegisterWorkflowResponse\".\x82\xd3\xe4\x93\x02(:\x01*\"#/v1/projects/{project_id}/workflows\x12\x83\x01\n" +
	"\rListWorkflows\x12!.workflow.v1.ListWorkflowsRequest\x1a\".workflow.v1.ListWorkflowsResponse\"+\x82\xd3\xe4\x93\x02%\x12#/v1/projects/{project_id}/workflows\x12\x8b\x01\n" +
	"\vGetWorkflow\x12\x1f.workflow.v1.GetWorkflowRequest\x1a .workflow.v1.GetWorkflowResponse\"9\x82\xd3\xe4\x93\x023\x121/v1/projects/{project_id}/workflows/{workflow_id}\x12\x87\x01\n" +
	"\rStartWorkflow\x12!.workflow.v1.StartWorkflowRequest\x1a\".workflow.v1.StartWorkflowResponse\"/\x82\xd3\xe4\x93\x02):\x01*\"$/v1/projects/{project_id}/executions\x12\x90\x01\n" +
	"\fGetExecution\x12 .workflow.v1.GetExecutionRequest\x1a!.workflow.v1.GetExecutionResponse\";\x82\xd3\xe4\x93\x025\x123/v1/projects/{project_id}/executions/{execution_id}\x12\x87\x01\n" +
	"\x0eListExecutions\x12\".workflow.v1.ListExecutionsRequest\x1a#.workflow.v1.ListExecutionsResponse\",\x82\xd3\xe4\x93\x02&\x12$/v1/projects/{project_id}/executions\x12\x95\x01\n" +
	"\x11GetDashboardStats\x12%.workflow.v1.GetDashboardStatsRequest\x1a&.workflow.v1.GetDashboardStatsResponse\"1\x82\xd3\xe4\x93\x02+\x12)/v1/projects/{project_id}/dashboard/stats\x12\xb1\x01\n" +
	"\x14GetExecutionTimeline\x12(.workflow.v1.GetExecutionTimelineRequest\x1a).workflow.v1.GetExecutionTimelineResponse\"D\x82\xd3\xe4\x93\x02>\x12</v1/projects/{project_id}/executions/{execution_id}/timeline2\xa8\x03\n" +
	"\rModuleService\x12\x87\x01\n" +
	"\x0eRegisterModule\x12\".workflow.v1.RegisterModuleRequest\x1a#.workflow.v1.RegisterModuleResponse\",\x82\xd3\xe4\x93\x02&:\x01*\"!/v1/projects/{project_id}/modules\x12\x8f\x01\n" +
	"\tGetModule\x12\x1d.workflow.v1.GetModuleRequest\x1a\x1e.workflow.v1.GetModuleResponse\"C\x82\xd3\xe4\x93\x02=\x12;/v1/projects/{project_id}/modules/{name}/versions/{version}\x12{\n" +
	"\vListModules\x12\x1f.workflow.v1.ListModulesRequest\x1a .workflow.v1.ListModulesResponse\")\x82\xd3\xe4\x93\x02#\x12!/v1/projects/{project_id}/modulesB\xbd\x01\x92A{\x12R\n" +
	"\x13Workflow Engine API\x127Control-plane API for workflow validation and execution2\x02v1*\x01\x022\x10application/json:\x10application/jsonZ=github.com/prashantsinghb/workflow-engine/api/service;serviceb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 46)
var file_service_proto_goTypes = []any{
	(ExecutionState)(0),                  // 0: workflow.v1.ExecutionState
	(*WorkflowDefinition)(nil),           // 1: workflow.v1.WorkflowDefinition
	(*ValidateWorkflowRequest)(nil),      // 2: workflow.v1.ValidateWorkflowRequest
	(*ValidateWorkflowResponse)(nil),     // 3: workflow.v1.ValidateWorkflowResponse
	(*RegisterWorkflowRequest)(nil),      // 4: workflow.v1.RegisterWorkflowRequest
	(*RegisterWorkflowResponse)(nil),     // 5: workflow.v1.RegisterWorkflowResponse
	(*ListWorkflowsRequest)(nil),         // 6: workflow.v1.ListWorkflowsRequest
	(*ListWorkflowsResponse)(nil),        // 7: workflow.v1.ListWorkflowsResponse
	(*WorkflowInfo)(nil),                 // 8: workflow.v1.WorkflowInfo
	(*GetWorkflowRequest)(nil),           // 9: workflow.v1.GetWorkflowRequest
	(*GetWorkflowResponse)(nil),          // 10: workflow.v1.GetWorkflowResponse
	(*StartWorkflowRequest)(nil),         // 11: workflow.v1.StartWorkflowRequest
	(*StartWorkflowResponse)(nil),        // 12: workflow.v1.StartWorkflowResponse
	(*GetExecutionRequest)(nil),          // 13: workflow.v1.GetExecutionRequest
	(*GetExecutionResponse)(nil),         // 14: workflow.v1.GetExecutionResponse
	(*Module)(nil),                       // 15: workflow.v1.Module
	(*HttpModuleSpec)(nil),               // 16: workflow.v1.HttpModuleSpec
	(*HttpAuth)(nil),                     // 17: workflow.v1.HttpAuth
	(*ApiKeyAuth)(nil),                   // 18: workflow.v1.ApiKeyAuth
	(*BearerAuth)(nil),                   // 19: workflow.v1.BearerAuth
	(*OAuth2Auth)(nil),                   // 20: workflow.v1.OAuth2Auth
	(*ContainerRegistryModuleSpec)(nil),  // 21: workflow.v1.ContainerRegistryModuleSpec
	(*RegisterModuleRequest)(nil),        // 22: workflow.v1.RegisterModuleRequest
	(*RegisterModuleResponse)(nil),       // 23: workflow.v1.RegisterModuleResponse
	(*GetModuleRequest)(nil),             // 24: workflow.v1.GetModuleRequest
	(*GetModuleResponse)(nil),            // 25: workflow.v1.GetModuleResponse
	(*ListModulesRequest)(nil),           // 26: workflow.v1.ListModulesRequest
	(*ListModulesResponse)(nil),          // 27: workflow.v1.ListModulesResponse
	(*ListExecutionsRequest)(nil),        // 28: workflow.v1.ListExecutionsRequest
	(*ExecutionInfo)(nil),                // 29: workflow.v1.ExecutionInfo
	(*ListExecutionsResponse)(nil),       // 30: workflow.v1.ListExecutionsResponse
	(*GetDashboardStatsRequest)(nil),     // 31: workflow.v1.GetDashboardStatsRequest
	(*GetDashboardStatsResponse)(nil),    // 32: workflow.v1.GetDashboardStatsResponse
	(*GetExecutionTimelineRequest)(nil),  // 33: workflow.v1.GetExecutionTimelineRequest
	(*GetExecutionTimelineResponse)(nil), // 34: workflow.v1.GetExecutionTimelineResponse
	(*ExecutionTimeline)(nil),            // 35: workflow.v1.ExecutionTimeline
	(*ExecutionTimelineEvent)(nil),       // 36: workflow.v1.ExecutionTimelineEvent
	nil,                                  // 37: workflow.v1.StartWorkflowRequest.InputsEntry
	nil,                                  // 38: workflow.v1.GetExecutionResponse.InputsEntry
	nil,                                  // 39: workflow.v1.GetExecutionResponse.OutputsEntry
	nil,                                  // 40: workflow.v1.Module.InputsEntry
	nil,                                  // 41: workflow.v1.Module.OutputsEntry
	nil,                                  // 42: workflow.v1.HttpModuleSpec.HeadersEntry
	nil,                                  // 43: workflow.v1.HttpModuleSpec.QueryParamsEntry
	nil,                                  // 44: workflow.v1.ContainerRegistryModuleSpec.EnvEntry
	nil,                                  // 45: workflow.v1.RegisterModuleRequest.InputsEntry
	nil,                                  // 46: workflow.v1.RegisterModuleRequest.OutputsEntry
	(*structpb.Struct)(nil),              // 47: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),        // 48: google.protobuf.Timestamp
	(*structpb.Value)(nil),               // 49: google.protobuf.Value
}
var file_service_proto_depIdxs = []int32{
	1,  // 0: workflow.v1.ValidateWorkflowRequest.workflow:type_name -> workflow.v1.WorkflowDefinition
	1,  // 1: workflow.v1.RegisterWorkflowRequest.workflow:type_name -> workflow.v1.WorkflowDefinition
	8,  // 2: workflow.v1.ListWorkflowsResponse.workflows:type_name -> workflow.v1.WorkflowInfo
	8,  // 3: workflow.v1.GetWorkflowResponse.workflow:type_name -> workflow.v1.WorkflowInfo
	37, // 4: workflow.v1.StartWorkflowRequest.inputs:type_name -> workflow.v1.StartWorkflowRequest.InputsEntry
	0,  // 5: workflow.v1.GetExecutionResponse.state:type_name -> workflow.v1.ExecutionState
	38, // 6: workflow.v1.GetExecutionResponse.inputs:type_name -> workflow.v1.GetExecutionResponse.InputsEntry
	39, // 7: workflow.v1.GetExecutionResponse.outputs:type_name -> workflow.v1.GetExecutionResponse.OutputsEntry
	16, // 8: workflow.v1.Module.http:type_name -> workflow.v1.HttpModuleSpec
	21, // 9: workflow.v1.Module.container_registry:type_name -> workflow.v1.ContainerRegistryModuleSpec
	40, // 10: workflow.v1.Module.inputs:type_name -> workflow.v1.Module.InputsEntry
	41, // 11: workflow.v1.Module.outputs:type_name -> workflow.v1.Module.OutputsEntry
	47, // 12: workflow.v1.Module.runtime_config:type_name -> google.protobuf.Struct
	42, // 13: workflow.v1.HttpModuleSpec.headers:type_name -> workflow.v1.HttpModuleSpec.HeadersEntry
	43, // 14: workflow.v1.HttpModuleSpec.query_params:type_name -> workflow.v1.HttpModuleSpec.QueryParamsEntry
	47, // 15: workflow.v1.HttpModuleSpec.body_template:type_name -> google.protobuf.Struct
	17, // 16: workflow.v1.HttpModuleSpec.auth:type_name -> workflow.v1.HttpAuth
	47, // 17: workflow.v1.HttpModuleSpec.output_mapping:type_name -> google.protobuf.Struct
	18, // 18: workflow.v1.HttpAuth.api_key:type_name -> workflow.v1.ApiKeyAuth
	19, // 19: workflow.v1.HttpAuth.bearer:type_name -> workflow.v1.BearerAuth
	20, // 20: workflow.v1.HttpAuth.oauth2:type_name -> workflow.v1.OAuth2Auth
	44, // 21: workflow.v1.ContainerRegistryModuleSpec.env:type_name -> workflow.v1.ContainerRegistryModuleSpec.EnvEntry
	16, // 22: workflow.v1.RegisterModuleRequest.http:type_name -> workflow.v1.HttpModuleSpec
	21, // 23: workflow.v1.RegisterModuleRequest.container_registry:type_name -> workflow.v1.ContainerRegistryModuleSpec
	45, // 24: workflow.v1.RegisterModuleRequest.inputs:type_name -> workflow.v1.RegisterModuleRequest.InputsEntry
	46, // 25: workflow.v1.RegisterModuleRequest.outputs:type_name -> workflow.v1.RegisterModuleRequest.OutputsEntry
	15, // 26: workflow.v1.GetModuleResponse.module:type_name -> workflow.v1.Module
	15, // 27: workflow.v1.ListModulesResponse.modules:type_name -> workflow.v1.Module
	29, // 28: workflow.v1.ListExecutionsResponse.executions:type_name -> workflow.v1.ExecutionInfo
	35, // 29: workflow.v1.GetExecutionTimelineResponse.timeline:type_name -> workflow.v1.ExecutionTimeline
	48, // 30: workflow.v1.ExecutionTimeline.started_at:type_name -> google.protobuf.Timestamp
	48, // 31: workflow.v1.ExecutionTimeline.completed_at:type_name -> google.protobuf.Timestamp
	36, // 32: workflow.v1.ExecutionTimeline.events:type_name -> workflow.v1.ExecutionTimelineEvent
	48, // 33: workflow.v1.ExecutionTimelineEvent.timestamp:type_name -> google.protobuf.Timestamp
	47, // 34: workflow.v1.ExecutionTimelineEvent.payload:type_name -> google.protobuf.Struct
	49, // 35: workflow.v1.StartWorkflowRequest.InputsEntry.value:type_name -> google.protobuf.Value
	49, // 36: workflow.v1.GetExecutionResponse.InputsEntry.value:type_name -> google.protobuf.Value
	49, // 37: workflow.v1.GetExecutionResponse.OutputsEntry.value:type_name -> google.protobuf.Value
	49, // 38: workflow.v1.Module.InputsEntry.value:type_name -> google.protobuf.Value
	49, // 39: workflow.v1.Module.OutputsEntry.value:type_name -> google.protobuf.Value
	49, // 40: workflow.v1.RegisterModuleRequest.InputsEntry.value:type_name -> google.protobuf.Value
	49, // 41: workflow.v1.RegisterModuleRequest.OutputsEntry.value:type_name -> google.protobuf.Value
	2,  // 42: workflow.v1.WorkflowService.ValidateWorkflow:input_type -> workflow.v1.ValidateWorkflowRequest
	4,  // 43: workflow.v1.WorkflowService.RegisterWorkflow:input_type -> workflow.v1.RegisterWorkflowRequest
	6,  // 44: workflow.v1.WorkflowService.ListWorkflows:input_type -> workflow.v1.ListWorkflowsRequest
	9,  // 45: workflow.v1.WorkflowService.GetWorkflow:input_type -> workflow.v1.GetWorkflowRequest
	11, // 46: workflow.v1.WorkflowService.StartWorkflow:input_type -> workflow.v1.StartWorkflowRequest
	13, // 47: workflow.v1.WorkflowService.GetExecution:input_type -> workflow.v1.GetExecutionRequest
	28, // 48: workflow.v1.WorkflowService.ListExecutions:input_type -> workflow.v1.ListExecutionsRequest
	31, // 49: workflow.v1.WorkflowService.GetDashboardStats:input_type -> workflow.v1.GetDashboardStatsRequest
	33, // 50: workflow.v1.WorkflowService.GetExecutionTimeline:input_type -> workflow.v1.GetExecutionTimelineRequest
	22, // 51: workflow.v1.ModuleService.RegisterModule:input_type -> workflow.v1.RegisterModuleRequest
	24, // 52: workflow.v1.ModuleService.GetModule:input_type -> workflow.v1.GetModuleRequest
	26, // 53: workflow.v1.ModuleService.ListModules:input_type -> workflow.v1.ListModulesRequest
	3,  // 54: workflow.v1.WorkflowService.ValidateWorkflow:output_type -> workflow.v1.ValidateWorkflowResponse
	5,  // 55: workflow.v1.WorkflowService.RegisterWorkflow:output_type -> workflow.v1.RegisterWorkflowResponse
	7,  // 56: workflow.v1.WorkflowService.ListWorkflows:output_type -> workflow.v1.ListWorkflowsResponse
	10, // 57: workflow.v1.WorkflowService.GetWorkflow:output_type -> workflow.v1.GetWorkflowResponse
	12, // 58: workflow.v1.WorkflowService.StartWorkflow:output_type -> workflow.v1.StartWorkflowResponse
	14, // 59: workflow.v1.WorkflowService.GetExecution:output_type -> workflow.v1.GetExecutionResponse
	30, // 60: workflow.v1.WorkflowService.ListExecutions:output_type -> workflow.v1.ListExecutionsResponse
	32, // 61: workflow.v1.WorkflowService.GetDashboardStats:output_type -> workflow.v1.GetDashboardStatsResponse
	34, // 62: workflow.v1.WorkflowService.GetExecutionTimeline:output_type -> workflow.v1.GetExecutionTimelineResponse
	23, // 63: workflow.v1.ModuleService.RegisterModule:output_type -> workflow.v1.RegisterModuleResponse
	25, // 64: workflow.v1.ModuleService.GetModule:output_type -> workflow.v1.GetModuleResponse
	27, // 65: workflow.v1.ModuleService.ListModules:output_type -> workflow.v1.ListModulesResponse
	54, // [54:66] is the sub-list for method output_type
	42, // [42:54] is the sub-list for method input_type
	42, // [42:42] is the sub-list for extension type_name
	42, // [42:42] is the sub-list for extension extendee
	0,  // [0:42] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_service_proto_msgTypes[14].OneofWrappers = []any{
		(*Module_Http)(nil),
		(*Module_ContainerRegistry)(nil),
	}
	file_service_proto_msgTypes[16].OneofWrappers = []any{
		(*HttpAuth_ApiKey)(nil),
		(*HttpAuth_Bearer)(nil),
		(*HttpAuth_Oauth2)(nil),
	}
	file_service_proto_msgTypes[21].OneofWrappers = []any{
		(*RegisterModuleRequest_Http)(nil),
		(*RegisterModuleRequest_ContainerRegistry)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   46,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		EnumInfos:         file_service_proto_enumTypes,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
