// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: pkg/proto/step_executor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request from engine to microservice to execute a step
type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Step          string                 `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`
	Input         map[string]string      `protobuf:"bytes,2,rep,name=input,proto3" json:"input,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // string map for simplicity
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_pkg_proto_step_executor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_step_executor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_step_executor_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *ExecuteRequest) GetInput() map[string]string {
	if x != nil {
		return x.Input
	}
	return nil
}

// Response from microservice
type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        map[string]string      `protobuf:"bytes,1,rep,name=output,proto3" json:"output,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // string map
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                                                                             // empty if no error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_pkg_proto_step_executor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_step_executor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_step_executor_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteResponse) GetOutput() map[string]string {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_proto_step_executor_proto protoreflect.FileDescriptor

const file_pkg_proto_step_executor_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/proto/step_executor.proto\x12\x05proto\"\x96\x01\n" +
	"\x0eExecuteRequest\x12\x12\n" +
	"\x04step\x18\x01 \x01(\tR\x04step\x126\n" +
	"\x05input\x18\x02 \x03(\v2 .proto.ExecuteRequest.InputEntryR\x05input\x1a8\n" +
	"\n" +
	"InputEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9e\x01\n" +
	"\x0fExecuteResponse\x12:\n" +
	"\x06output\x18\x01 \x03(\v2\".proto.ExecuteResponse.OutputEntryR\x06output\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x1a9\n" +
	"\vOutputEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012L\n" +
	"\fStepExecutor\x12<\n" +
	"\vExecuteStep\x12\x15.proto.ExecuteRequest\x1a\x16.proto.ExecuteResponseB;Z9github.com/prashantsinghb/workflow-engine/pkg/proto;protob\x06proto3"

var (
	file_pkg_proto_step_executor_proto_rawDescOnce sync.Once
	file_pkg_proto_step_executor_proto_rawDescData []byte
)

func file_pkg_proto_step_executor_proto_rawDescGZIP() []byte {
	file_pkg_proto_step_executor_proto_rawDescOnce.Do(func() {
		file_pkg_proto_step_executor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_step_executor_proto_rawDesc), len(file_pkg_proto_step_executor_proto_rawDesc)))
	})
	return file_pkg_proto_step_executor_proto_rawDescData
}

var file_pkg_proto_step_executor_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_proto_step_executor_proto_goTypes = []any{
	(*ExecuteRequest)(nil),  // 0: proto.ExecuteRequest
	(*ExecuteResponse)(nil), // 1: proto.ExecuteResponse
	nil,                     // 2: proto.ExecuteRequest.InputEntry
	nil,                     // 3: proto.ExecuteResponse.OutputEntry
}
var file_pkg_proto_step_executor_proto_depIdxs = []int32{
	2, // 0: proto.ExecuteRequest.input:type_name -> proto.ExecuteRequest.InputEntry
	3, // 1: proto.ExecuteResponse.output:type_name -> proto.ExecuteResponse.OutputEntry
	0, // 2: proto.StepExecutor.ExecuteStep:input_type -> proto.ExecuteRequest
	1, // 3: proto.StepExecutor.ExecuteStep:output_type -> proto.ExecuteResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_proto_step_executor_proto_init() }
func file_pkg_proto_step_executor_proto_init() {
	if File_pkg_proto_step_executor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_step_executor_proto_rawDesc), len(file_pkg_proto_step_executor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_step_executor_proto_goTypes,
		DependencyIndexes: file_pkg_proto_step_executor_proto_depIdxs,
		MessageInfos:      file_pkg_proto_step_executor_proto_msgTypes,
	}.Build()
	File_pkg_proto_step_executor_proto = out.File
	file_pkg_proto_step_executor_proto_goTypes = nil
	file_pkg_proto_step_executor_proto_depIdxs = nil
}
