// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: pkg/proto/step_executor.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StepExecutor_ExecuteStep_FullMethodName = "/proto.StepExecutor/ExecuteStep"
)

// StepExecutorClient is the client API for StepExecutor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// gRPC service implemented by microservice
type StepExecutorClient interface {
	ExecuteStep(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
}

type stepExecutorClient struct {
	cc grpc.ClientConnInterface
}

func NewStepExecutorClient(cc grpc.ClientConnInterface) StepExecutorClient {
	return &stepExecutorClient{cc}
}

func (c *stepExecutorClient) ExecuteStep(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, StepExecutor_ExecuteStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StepExecutorServer is the server API for StepExecutor service.
// All implementations must embed UnimplementedStepExecutorServer
// for forward compatibility.
//
// gRPC service implemented by microservice
type StepExecutorServer interface {
	ExecuteStep(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	mustEmbedUnimplementedStepExecutorServer()
}

// UnimplementedStepExecutorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStepExecutorServer struct{}

func (UnimplementedStepExecutorServer) ExecuteStep(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteStep not implemented")
}
func (UnimplementedStepExecutorServer) mustEmbedUnimplementedStepExecutorServer() {}
func (UnimplementedStepExecutorServer) testEmbeddedByValue()                      {}

// UnsafeStepExecutorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StepExecutorServer will
// result in compilation errors.
type UnsafeStepExecutorServer interface {
	mustEmbedUnimplementedStepExecutorServer()
}

func RegisterStepExecutorServer(s grpc.ServiceRegistrar, srv StepExecutorServer) {
	// If the following call panics, it indicates UnimplementedStepExecutorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StepExecutor_ServiceDesc, srv)
}

func _StepExecutor_ExecuteStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StepExecutorServer).ExecuteStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StepExecutor_ExecuteStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StepExecutorServer).ExecuteStep(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StepExecutor_ServiceDesc is the grpc.ServiceDesc for StepExecutor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StepExecutor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.StepExecutor",
	HandlerType: (*StepExecutorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteStep",
			Handler:    _StepExecutor_ExecuteStep_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/step_executor.proto",
}
