// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: step_registry.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StepRegistry_RegisterSteps_FullMethodName = "/proto.StepRegistry/RegisterSteps"
)

// StepRegistryClient is the client API for StepRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StepRegistryClient interface {
	RegisterSteps(ctx context.Context, in *RegisterStepsRequest, opts ...grpc.CallOption) (*RegisterStepsResponse, error)
}

type stepRegistryClient struct {
	cc grpc.ClientConnInterface
}

func NewStepRegistryClient(cc grpc.ClientConnInterface) StepRegistryClient {
	return &stepRegistryClient{cc}
}

func (c *stepRegistryClient) RegisterSteps(ctx context.Context, in *RegisterStepsRequest, opts ...grpc.CallOption) (*RegisterStepsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterStepsResponse)
	err := c.cc.Invoke(ctx, StepRegistry_RegisterSteps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StepRegistryServer is the server API for StepRegistry service.
// All implementations must embed UnimplementedStepRegistryServer
// for forward compatibility.
type StepRegistryServer interface {
	RegisterSteps(context.Context, *RegisterStepsRequest) (*RegisterStepsResponse, error)
	mustEmbedUnimplementedStepRegistryServer()
}

// UnimplementedStepRegistryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStepRegistryServer struct{}

func (UnimplementedStepRegistryServer) RegisterSteps(context.Context, *RegisterStepsRequest) (*RegisterStepsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterSteps not implemented")
}
func (UnimplementedStepRegistryServer) mustEmbedUnimplementedStepRegistryServer() {}
func (UnimplementedStepRegistryServer) testEmbeddedByValue()                      {}

// UnsafeStepRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StepRegistryServer will
// result in compilation errors.
type UnsafeStepRegistryServer interface {
	mustEmbedUnimplementedStepRegistryServer()
}

func RegisterStepRegistryServer(s grpc.ServiceRegistrar, srv StepRegistryServer) {
	// If the following call panics, it indicates UnimplementedStepRegistryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StepRegistry_ServiceDesc, srv)
}

func _StepRegistry_RegisterSteps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterStepsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StepRegistryServer).RegisterSteps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StepRegistry_RegisterSteps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StepRegistryServer).RegisterSteps(ctx, req.(*RegisterStepsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StepRegistry_ServiceDesc is the grpc.ServiceDesc for StepRegistry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StepRegistry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.StepRegistry",
	HandlerType: (*StepRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterSteps",
			Handler:    _StepRegistry_RegisterSteps_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "step_registry.proto",
}
