// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: step_registry.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StepSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"` // grpc | http | docker
	Endpoint      string                 `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	InputSchema   map[string]string      `protobuf:"bytes,5,rep,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	OutputSchema  map[string]string      `protobuf:"bytes,6,rep,name=output_schema,json=outputSchema,proto3" json:"output_schema,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepSpec) Reset() {
	*x = StepSpec{}
	mi := &file_step_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepSpec) ProtoMessage() {}

func (x *StepSpec) ProtoReflect() protoreflect.Message {
	mi := &file_step_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepSpec.ProtoReflect.Descriptor instead.
func (*StepSpec) Descriptor() ([]byte, []int) {
	return file_step_registry_proto_rawDescGZIP(), []int{0}
}

func (x *StepSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StepSpec) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StepSpec) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *StepSpec) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *StepSpec) GetInputSchema() map[string]string {
	if x != nil {
		return x.InputSchema
	}
	return nil
}

func (x *StepSpec) GetOutputSchema() map[string]string {
	if x != nil {
		return x.OutputSchema
	}
	return nil
}

type RegisterStepsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Steps         []*StepSpec            `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterStepsRequest) Reset() {
	*x = RegisterStepsRequest{}
	mi := &file_step_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterStepsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterStepsRequest) ProtoMessage() {}

func (x *RegisterStepsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_step_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterStepsRequest.ProtoReflect.Descriptor instead.
func (*RegisterStepsRequest) Descriptor() ([]byte, []int) {
	return file_step_registry_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterStepsRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *RegisterStepsRequest) GetSteps() []*StepSpec {
	if x != nil {
		return x.Steps
	}
	return nil
}

type RegisterStepsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterStepsResponse) Reset() {
	*x = RegisterStepsResponse{}
	mi := &file_step_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterStepsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterStepsResponse) ProtoMessage() {}

func (x *RegisterStepsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_step_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterStepsResponse.ProtoReflect.Descriptor instead.
func (*RegisterStepsResponse) Descriptor() ([]byte, []int) {
	return file_step_registry_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterStepsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterStepsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_step_registry_proto protoreflect.FileDescriptor

const file_step_registry_proto_rawDesc = "" +
	"\n" +
	"\x13step_registry.proto\x12\x05proto\"\xfe\x02\n" +
	"\bStepSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x1a\n" +
	"\bendpoint\x18\x04 \x01(\tR\bendpoint\x12C\n" +
	"\finput_schema\x18\x05 \x03(\v2 .proto.StepSpec.InputSchemaEntryR\vinputSchema\x12F\n" +
	"\routput_schema\x18\x06 \x03(\v2!.proto.StepSpec.OutputSchemaEntryR\foutputSchema\x1a>\n" +
	"\x10InputSchemaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a?\n" +
	"\x11OutputSchemaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"W\n" +
	"\x14RegisterStepsRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12%\n" +
	"\x05steps\x18\x02 \x03(\v2\x0f.proto.StepSpecR\x05steps\"K\n" +
	"\x15RegisterStepsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2Z\n" +
	"\fStepRegistry\x12J\n" +
	"\rRegisterSteps\x12\x1b.proto.RegisterStepsRequest\x1a\x1c.proto.RegisterStepsResponseB;Z9github.com/prashantsinghb/workflow-engine/pkg/proto;protob\x06proto3"

var (
	file_step_registry_proto_rawDescOnce sync.Once
	file_step_registry_proto_rawDescData []byte
)

func file_step_registry_proto_rawDescGZIP() []byte {
	file_step_registry_proto_rawDescOnce.Do(func() {
		file_step_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_step_registry_proto_rawDesc), len(file_step_registry_proto_rawDesc)))
	})
	return file_step_registry_proto_rawDescData
}

var file_step_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_step_registry_proto_goTypes = []any{
	(*StepSpec)(nil),              // 0: proto.StepSpec
	(*RegisterStepsRequest)(nil),  // 1: proto.RegisterStepsRequest
	(*RegisterStepsResponse)(nil), // 2: proto.RegisterStepsResponse
	nil,                           // 3: proto.StepSpec.InputSchemaEntry
	nil,                           // 4: proto.StepSpec.OutputSchemaEntry
}
var file_step_registry_proto_depIdxs = []int32{
	3, // 0: proto.StepSpec.input_schema:type_name -> proto.StepSpec.InputSchemaEntry
	4, // 1: proto.StepSpec.output_schema:type_name -> proto.StepSpec.OutputSchemaEntry
	0, // 2: proto.RegisterStepsRequest.steps:type_name -> proto.StepSpec
	1, // 3: proto.StepRegistry.RegisterSteps:input_type -> proto.RegisterStepsRequest
	2, // 4: proto.StepRegistry.RegisterSteps:output_type -> proto.RegisterStepsResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_step_registry_proto_init() }
func file_step_registry_proto_init() {
	if File_step_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_step_registry_proto_rawDesc), len(file_step_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_step_registry_proto_goTypes,
		DependencyIndexes: file_step_registry_proto_depIdxs,
		MessageInfos:      file_step_registry_proto_msgTypes,
	}.Build()
	File_step_registry_proto = out.File
	file_step_registry_proto_goTypes = nil
	file_step_registry_proto_depIdxs = nil
}
